// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ... existing code ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs71dyUoKH02cE__qs55w8HdyRhHZyzyk',
    appId: '1:690202805848:web:f6fd01e8f82c6f79506c2d',
    messagingSenderId: '690202805848',
    projectId: 'smart-ai-finance-tracker',
    authDomain: 'smart-ai-finance-tracker.firebaseapp.com',
    databaseURL: 'https://smart-ai-finance-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ai-finance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs71dyUoKH02cE__qs55w8HdyRhHZyzyk',
    appId: '1:690202805848:android:35f0681a2fee8442506c2d',
    messagingSenderId: '690202805848',
    projectId: 'smart-ai-finance-tracker',
    databaseURL: 'https://smart-ai-finance-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ai-finance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPYrMf-p0e8aRqLeeLGHx8yd6GpJWWtc',
    appId: '1:690202805848:ios:43c5e5f97c1c8479506c2d',
    messagingSenderId: '690202805848',
    projectId: 'smart-ai-finance-tracker',
    databaseURL: 'https://smart-ai-finance-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ai-finance-tracker.firebasestorage.app',
    iosClientId: '690202805848-hkocv6jvc0tts3r7sqbt18lsomva31rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtPYrMf-p0e8aRqLeeLGHx8yd6GpJWWtc',
    appId: '1:690202805848:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '690202805848',
    projectId: 'smart-ai-finance-tracker',
    databaseURL: 'https://smart-ai-finance-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ai-finance-tracker.firebasestorage.app',
    iosClientId: '690202805848-hkocv6jvc0tts3r7sqbt18lsomva31rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs71dyUoKH02cE__qs55w8HdyRhHZyzyk',
    appId: '1:690202805848:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '690202805848',
    projectId: 'smart-ai-finance-tracker',
    databaseURL: 'https://smart-ai-finance-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ai-finance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBs71dyUoKH02cE__qs55w8HdyRhHZyzyk',
    appId: '1:690202805848:linux:YOUR_LINUX_APP_ID',
    messagingSenderId: '690202805848',
    projectId: 'smart-ai-finance-tracker',
    databaseURL: 'https://smart-ai-finance-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ai-finance-tracker.firebasestorage.app',
  );
}